const $=id=>document.getElementById(id),notice=$('notice');let servants=[],visible=[],picked=new Set();
function msg(t,e=false){notice.textContent=t;notice.className='notice'+(e?' error':'');setTimeout(()=>notice.classList.add('hidden'),5000)}
function busy(b,on,t){b.disabled=on;if(on){b.dataset.old=b.textContent;b.textContent=t}else b.textContent=b.dataset.old||b.textContent}
async function api(url,opt={}){let r=await fetch(url,opt),d;try{d=await r.json()}catch{d={detail:'服务器返回内容无法读取'}}if(!r.ok)throw Error(d.detail||`请求失败 ${r.status}`);return d}
$('syncBtn').onclick=async()=>{let b=$('syncBtn');busy(b,true,'同步中…');try{let d=await api('/api/game-data/sync/CN',{method:'POST'});$('syncState').textContent=`${d.counts.servants} 位从者 · ${d.counts.equips} 张礼装`;msg('国服资料同步完成')}catch(e){msg(e.message,true)}finally{busy(b,false)}};
$('importBtn').onclick=async()=>{let content=$('captureText').value.trim();if(!content)return msg('请先粘贴 ey 开头的完整抓包内容',true);let b=$('importBtn');busy(b,true,'识别中…');try{let d=await api('/api/account/import-text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});$('accountState').textContent=`${d.servants} 位从者 · ${d.equips} 张礼装`;await load();msg('账号识别成功')}catch(e){msg(e.message,true)}finally{busy(b,false)}};
let jsonFile=null;
$('jsonFile').onchange=async e=>{jsonFile=e.target.files[0]||null;$('jsonProfile').classList.add('hidden');$('jsonProfile').innerHTML='';if(!jsonFile)return;try{let data=JSON.parse(await jsonFile.text()),profiles=(data.users||[]).map((u,index)=>({u,index})).filter(x=>String(x.u.region||'').toLowerCase()==='cn');if(!profiles.length)throw Error('文件中没有国服账号');profiles.forEach((x,i)=>$('jsonProfile').add(new Option(x.u.name||`国服账号 ${i+1}`,x.index)));if(profiles.length>1)$('jsonProfile').classList.remove('hidden');msg(`已读取文件：找到 ${profiles.length} 个国服账号`)}catch(e){jsonFile=null;$('jsonFile').value='';msg(`JSON 无法识别：${e.message}`,true)}};
$('jsonImportBtn').onclick=async()=>{if(!jsonFile)return msg('请先选择 Chaldea 导出的 JSON 文件',true);let b=$('jsonImportBtn'),form=new FormData();form.append('file',jsonFile);if($('jsonProfile').options.length)form.append('profile_index',$('jsonProfile').value);busy(b,true,'导入中…');try{let d=await api('/api/account/import',{method:'POST',body:form});if(d.needsProfile)throw Error('文件中有多个国服账号，请选择一个');$('accountState').textContent=`${d.servants} 位从者 · ${d.equips} 张礼装`;await load();msg('Chaldea JSON 导入成功')}catch(e){msg(e.message,true)}finally{busy(b,false)}};
async function load(){let d=await api('/api/account/servants');servants=d.servants;picked.clear();buildFilters();filter()}
function buildFilters(){const cn={saber:'剑阶',archer:'弓阶',lancer:'枪阶',rider:'骑阶',caster:'术阶',assassin:'杀阶',berserker:'狂阶',ruler:'裁阶',avenger:'仇阶',moonCancer:'月癌',alterEgo:'丑阶',foreigner:'降临者',pretender:'伪阶',shielder:'盾阶',beast:'兽阶'};let classes=[...new Set(servants.map(s=>s.className).filter(Boolean))].sort(),traits=new Map();servants.forEach(s=>s.traits.forEach(t=>traits.set(t.id,t.name)));$('classFilter').innerHTML='<option value="">全部职阶</option>'+classes.map(x=>`<option value="${x}">${cn[x]||x}</option>`).join('');let opts='<option value="">不限</option>'+[...traits].sort((a,b)=>a[1].localeCompare(b[1],'zh-CN')).map(([id,n])=>`<option value="${id}">${n}</option>`).join('');$('traitA').innerHTML=opts;$('traitB').innerHTML=opts}
function filter(){let cls=$('classFilter').value,a=+$('traitA').value,b=+$('traitB').value,q=$('search').value.trim().toLowerCase();visible=servants.filter(s=>(!cls||s.className===cls)&&(!a||s.traits.some(t=>t.id===a))&&(!b||s.traits.some(t=>t.id===b))&&(!q||s.name.toLowerCase().includes(q)));$('candidateCount').textContent=`符合条件：${visible.length} 位`;$('analyzeBtn').disabled=!visible.length;drawServants()}
function drawServants(){let list=$('servantList');list.innerHTML=visible.length?visible.map(s=>`<button class="servant-card ${picked.has(s.id)?'picked':''}" data-id="${s.id}">${s.face?`<img src="${s.face}" alt="">`:`<span class="avatar">${s.name[0]}</span>`}<strong>${s.name}</strong><small>${s.className}${s.level?` · Lv.${s.level}`:''}${s.bond?` · 羁绊${s.bond}`:''}</small><i>${picked.has(s.id)?'已选':'选择'}</i></button>`).join(''):'<div class="empty">没有符合条件的从者</div>';list.querySelectorAll('.servant-card').forEach(el=>el.onclick=()=>toggle(+el.dataset.id))}
function toggle(id){if(picked.has(id))picked.delete(id);else if(picked.size<6)picked.add(id);else return msg('队伍最多 6 名从者',true);drawServants();drawPicked()}
function drawPicked(){let rows=servants.filter(s=>picked.has(s.id));$('pickedList').innerHTML=rows.length?rows.map(s=>`<button onclick="window.removePicked(${s.id})">${s.face?`<img src="${s.face}" alt="">`:''}<span>${s.name}</span><i>×</i></button>`).join(''):'<div class="empty">尚未选择</div>';$('selectedCount').textContent=`已选择 ${picked.size} / 6`}
window.removePicked=id=>toggle(id);
['classFilter','traitA','traitB'].forEach(id=>$(id).onchange=filter);$('search').oninput=filter;
$('analyzeBtn').onclick=async()=>{let b=$('analyzeBtn');busy(b,true,'正在分析…');try{let d=await api('/api/bond/recommend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({servant_ids:visible.map(s=>s.id),selected_ids:[...picked]})});drawAnalysis(d)}catch(e){msg(e.message,true)}finally{busy(b,false)}};
function drawAnalysis(d){$('analysis').classList.remove('hidden');$('ceList').innerHTML=d.recommendations.length?d.recommendations.map((r,i)=>`<article class="ce-result"><div class="ce-left"><span class="rank">${i+1}</span>${r.icon?`<img src="${r.icon}" alt="${r.name}">`:'<div class="ce-placeholder">CE</div>'}<strong>${r.name}</strong><small>${r.target} · +${r.percent}%</small></div><div class="ce-right"><div class="coverage-title">推荐 6 人组合 <b>覆盖 ${r.coverage}/${r.candidateCount}</b></div><div class="portrait-row">${r.suggested.map(x=>`<button class="portrait ${x.selected?'locked':''}" data-sid="${x.id}">${x.face?`<img src="${x.face}" alt="">`:`<span>${x.name[0]}</span>`}<small>${x.name}</small>${x.selected?'<i>已选</i>':''}</button>`).join('')}</div><details><summary>查看全部 ${r.coverage} 名适用从者</summary><div class="portrait-row all">${r.covered.map(x=>`<button class="portrait" data-sid="${x.id}">${x.face?`<img src="${x.face}" alt="">`:`<span>${x.name[0]}</span>`}<small>${x.name}</small></button>`).join('')}</div></details></div></article>`).join(''):'<div class="panel empty">没有礼装能同时覆盖你已选的从者。可以减少已选从者，或放宽上方筛选条件。</div>';document.querySelectorAll('.portrait').forEach(el=>el.onclick=()=>toggle(+el.dataset.sid));$('analysis').scrollIntoView({behavior:'smooth'})}
fetch('/api/account').then(r=>r.ok?load():null).catch(()=>{});
